title: "homelab"
email: ""
description: "Homelab Hardware, Apps und Setup"
author: "crss"

# Domain-Setup
url: "https://spectra.moyonet.de"
baseurl: ""

# Clean Blog Theme von StartBootstrap
remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll

# Social Profiles (optional)
twitter_username:
github_username: crss
facebook_username:
instagram_username:
linkedin_username:

# Analytics (optional)
google_analytics: ""

# Build Settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jekyll-sitemap   # kannst du aktivieren, wenn du willst