title: "homelab"
email: "cratruenas@gmail.com"
description: "Homelab Hardware, Apps und Setup"
author: "crss"

# Domain-Setup
url: "https://spectra.moyonet.de"
baseurl: ""

# Clean Blog Theme von StartBootstrap
remote_theme: pages-themes/hacker

# Optional
show_downloads: false
google_analytics: ""

# Social Profiles (optional)
twitter_username:
github_username: crss
facebook_username:
instagram_username:
linkedin_username:

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate
  # - jekyll-sitemap   # kannst du aktivieren, wenn du willst